# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -Xverify:none
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.igrium.worldexport
archives_base_name=worldexport

# Dependencies
fabric_version=0.119.3+1.21.4