# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=1.3.2
maven_group=com.igrium.worldexport
archives_base_name=worldexport

# Dependencies
fabric_version=0.155.2+26.2
replaymod_version=26.2-2.6.27
craftui_version=0.8.0-b2